### ISSUE TITLE
OpenSSL dependency error on Fedora 36

### ISSUE THREAD

**Issue by 0x6d69636b** [Riduidel/rrss2imap#65]
After upgrading to Fedora 36 rrss2imap does not run anymore:
```
rrss2imap: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
rrss2imap: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
Fedora installs OpenSSL in Version 3.0.3, the installation of OpenSSL 1.1 solved the error messages:
```
sudo dnf install openssl1.1
```
However, I would really appreciate it if you could update the dependencies :-)

**Comment by Riduidel** [comment]
Catching up with old issues, will try to take care of your problem

**Comment by Riduidel** [comment]
Sorry for the late reply. Can you test the executable in https://github.com/Riduidel/rrss2imap/actions/runs/5235638594 ? (it now seems to work on my raspbian, but I have some problems with GitHub actions asset publication)

**Comment by 0x6d69636b** [comment]
No worries. I'm on Fedora 38 now, and it works with version 0.4.0! :+1:
