### ISSUE TITLE
Fetch full entry content

### ISSUE THREAD

**Issue by rakoo** [Riduidel/rrss2imap#78]
First of all, thank you very much for your project !

I have multiple feeds where the entries are only a summary of the full content, and I would like to have the full content fetched and available offline. Is there a possibility to do that ?

**Comment by Riduidel** [comment]
In fact, it's not in the scope of rrss2imap. For such a purpose, I suggest you use [rss-bridge](https://rss-bridge.github.io/rss-bridge/), a delicious php project exposing modified rss feeds

**Comment by rakoo** [comment]
Interesting, I didn't know rss-bridge and the likes could fetch the whole content on top of an existing rss feed. But indeed, it is probably more in their scope.
